=== hyndex/DC-OCPP/configs/ocpp/v16/profile_schemas/Config.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Json schema for OCPP 1.6 config",
    "type": "object",
    "required": [
        "Internal",
        "Core",
        "Security"
    ],
    "properties": {
        "Internal": {
            "type": "object",
            "$ref": "Internal.json"
        },
        "Core": {
            "type": "object",
            "$ref": "Core.json"
        },
        "LocalAuthListManagement": {
            "type": "object",
            "$ref": "LocalAuthListManagement.json"
        },
        "SmartCharging": {
            "type": "object",
            "$ref": "SmartCharging.json"
        },
        "FirmwareManagement": {
            "type": "object",
            "$ref": "FirmwareManagement.json"
        },
        "Reservation": {
            "type": "object",
            "$ref": "Reservation.json"
        },
        "Security": {
            "type": "object",
            "$ref": "Security.json"
        },
        "PnC": {
            "type": "object",
            "$ref": "PnC.json"
        },
        "CostAndPrice": {
            "type": "object",
            "$ref": "CostAndPrice.json"
        },
        "Custom": {
            "type": "object",
            "$ref": "Custom.json"
        }
    },
    "additionalProperties": false
}

=== hyndex/DC-OCPP/configs/ocpp16-config.json
{
  "Internal": {
    "ChargePointId": "jp-dc-01",
    "CentralSystemURI": "ws://127.0.0.1:8180/steve/websocket/CentralSystemService/",
    "ChargeBoxSerialNumber": "jp-dc-01",
    "ChargePointModel": "Joulepoint-DC",
    "ChargePointVendor": "JoulePoint",
    "FirmwareVersion": "0.0.1",
    "LogMessagesFormat": []
  },
  "Core": {
    "AuthorizeRemoteTxRequests": true,
    "ClockAlignedDataInterval": 900,
    "ConnectionTimeOut": 10,
    "ConnectorPhaseRotation": "0.RST,1.RST,2.RST,3.RST,4.RST,5.RST,6.RST,7.RST,8.RST,9.RST,10.RST,11.RST,12.RST",
    "GetConfigurationMaxKeys": 100,
    "HeartbeatInterval": 300,
    "LocalAuthorizeOffline": false,
    "LocalPreAuthorize": false,
    "MeterValuesAlignedData": "Energy.Active.Import.Register",
    "MeterValuesSampledData": "Energy.Active.Import.Register",
    "MeterValueSampleInterval": 0,
    "NumberOfConnectors": 12,
    "ResetRetries": 1,
    "StopTransactionOnEVSideDisconnect": true,
    "StopTransactionOnInvalidId": true,
    "StopTxnAlignedData": "Energy.Active.Import.Register",
    "StopTxnSampledData": "Energy.Active.Import.Register",
    "SupportedFeatureProfiles": "Core,FirmwareManagement,RemoteTrigger,Reservation,LocalAuthListManagement,SmartCharging",
    "TransactionMessageAttempts": 1,
    "TransactionMessageRetryInterval": 10,
    "UnlockConnectorOnEVSideDisconnect": true
  },
  "FirmwareManagement": {
    "SupportedFileTransferProtocols": "HTTPS"
  },
  "LocalAuthListManagement": {
    "LocalAuthListEnabled": true,
    "LocalAuthListMaxLength": 42,
    "SendLocalListMaxLength": 42
  },
  "SmartCharging": {
    "ChargeProfileMaxStackLevel": 42,
    "ChargingScheduleAllowedChargingRateUnit": "Current",
    "ChargingScheduleMaxPeriods": 42,
    "MaxChargingProfilesInstalled": 42
  },
  "Security": {
    "SecurityProfile": 0
  },
  "PnC": {
    "ISO15118CertificateManagementEnabled": false,
    "ISO15118PnCEnabled": false,
    "ContractValidationOffline": false
  },
  "CostAndPrice": {
    "CustomDisplayCostAndPrice": false
  }
}

=== hyndex/DC-OCPP/configs/ocpp/v16/config-full.json
{
    "Internal": {
        "ChargePointId": "cp001",
        "CentralSystemURI": "127.0.0.1:8180/steve/websocket/CentralSystemService/",
        "ChargeBoxSerialNumber": "cp001",
        "ChargePointModel": "Yeti",
        "ChargePointSerialNumber": "cp001",
        "ChargePointVendor": "Pionix",
        "FirmwareVersion": "0.1",
        "ICCID": "891004234814455936F",
        "IMSI": "262 01 9876543210",
        "MeterSerialNumber": "123-456-789",
        "MeterType": "AC",
        "SupportedCiphers12": [
            "ECDHE-ECDSA-AES128-GCM-SHA256",
            "ECDHE-ECDSA-AES256-GCM-SHA384",
            "AES128-GCM-SHA256",
            "AES256-GCM-SHA384"
        ],
        "SupportedCiphers13": [
            "TLS_AES_256_GCM_SHA384",
            "TLS_AES_128_GCM_SHA256"
        ],
        "UseTPM": false,
        "RetryBackoffRandomRange": 10,
        "RetryBackoffRepeatTimes": 3,
        "RetryBackoffWaitMinimum": 3,
        "AuthorizeConnectorZeroOnConnectorOne": true,
        "LogMessages": true,
        "LogMessagesFormat": [
            "log",
            "html",
            "session_logging",
            "security"
        ],
        "LogRotation": false,
        "LogRotationDateSuffix": false,
        "LogRotationMaximumFileSize": 0,
        "LogRotationMaximumFileCount": 0,
        "SupportedChargingProfilePurposeTypes": [
            "ChargePointMaxProfile",
            "TxDefaultProfile",
            "TxProfile"
        ],
        "MaxCompositeScheduleDuration": 31536000,
        "WebsocketPingPayload": "Hello from EVerest!",
        "WebsocketPongTimeout": 5,
        "UseSslDefaultVerifyPaths": true,
        "VerifyCsmsCommonName": true,
        "VerifyCsmsAllowWildcards": true,
        "OcspRequestInterval": 604800,
        "SeccLeafSubjectCommonName": "DEPNX100001",
        "SeccLeafSubjectCountry": "DE",
        "SeccLeafSubjectOrganization": "Pionix",
        "ConnectorEvseIds": "DE*PNX*100001,DE*PNX*100002",
        "AllowChargingProfileWithoutStartSchedule": false,
        "WaitForStopTransactionsOnResetTimeout": 60,
        "QueueAllMessages": true,
        "MessageTypesDiscardForQueueing": "Heartbeat",
        "MessageQueueSizeThreshold": 5000,
        "SupportedMeasurands": "Energy.Active.Import.Register,Energy.Active.Export.Register,Power.Active.Import,Voltage,Current.Import,Frequency,Current.Offered,Power.Offered,SoC",
        "MaxMessageSize": 65000,
        "TLSKeylogFile": "/tmp/ocpp_tls_keylog.txt",
        "EnableTLSKeylog": false
    },
    "Core": {
        "AllowOfflineTxForUnknownId": true,
        "AuthorizationCacheEnabled": true,
        "AuthorizeRemoteTxRequests": true,
        "BlinkRepeat": 0,
        "ClockAlignedDataInterval": 900,
        "ConnectionTimeOut": 120,
        "ConnectorPhaseRotation": "RST0.RST,1.RST,2.RTS",
        "ConnectorPhaseRotationMaxLength": 100,
        "GetConfigurationMaxKeys": 1024,
        "HeartbeatInterval": 900,
        "LightIntensity": 0,
        "LocalAuthorizeOffline": true,
        "LocalPreAuthorize": true,
        "MaxEnergyOnInvalidId": 500,
        "MeterValuesAlignedData": "Energy.Active.Import.Register",
        "MeterValuesAlignedDataMaxLength": 1024,
        "MeterValuesSampledData": "Energy.Active.Import.Register",
        "MeterValuesSampledDataMaxLength": 1024,
        "MeterValueSampleInterval": 300,
        "MinimumStatusDuration": 1,
        "NumberOfConnectors": 2,
        "ResetRetries": 1,
        "StopTransactionOnEVSideDisconnect": true,
        "StopTransactionOnInvalidId": true,
        "StopTxnAlignedData": "Energy.Active.Import.Register",
        "StopTxnAlignedDataMaxLength": 1024,
        "StopTxnSampledData": "Energy.Active.Import.Register",
        "StopTxnSampledDataMaxLength": 1024,
        "SupportedFeatureProfiles": "Core,FirmwareManagement,RemoteTrigger,Reservation,LocalAuthListManagement,SmartCharging",
        "SupportedFeatureProfilesMaxLength": 1024,
        "TransactionMessageAttempts": 1,
        "TransactionMessageRetryInterval": 10,
        "UnlockConnectorOnEVSideDisconnect": true,
        "WebSocketPingInterval": 10
    },
    "LocalAuthListManagement": {
        "LocalAuthListEnabled": true,
        "LocalAuthListMaxLength": 1024,
        "SendLocalListMaxLength": 1024
    },
    "SmartCharging": {
        "ChargeProfileMaxStackLevel": 1000,
        "ChargingScheduleAllowedChargingRateUnit": "Current,Power",
        "ChargingScheduleMaxPeriods": 1000,
        "ConnectorSwitch3to1PhaseSupported": true,
        "MaxChargingProfilesInstalled": 1000
    },
    "FirmwareManagement": {
        "SupportedFileTransferProtocols": "FTP,FTPS,HTTP,HTTPS"
    },
    "Reservation": {
        "ReserveConnectorZeroSupported": false
    },
    "Security": {
        "AdditionalRootCertificateCheck": false,
        "AuthorizationKey": "DEADBEEFDEADBEEF",
        "CertificateSignedMaxChainSize": 10000,
        "CertificateStoreMaxLength": 1000,
        "CpoName": "Pionix",
        "SecurityProfile": 1,
        "DisableSecurityEventNotifications": false
    },
    "CostAndPrice": {
        "CustomDisplayCostAndPrice": true,
        "NumberOfDecimalsForCostValues": 4,
        "DefaultPrice":
        {
            "priceText": "This is the price",
            "priceTextOffline": "Show this price text when offline!",
            "chargingPrice":
            {
                "kWhPrice": 3.14,
                "hourPrice": 0.42
            }
        },
        "DefaultPriceText":
        {
            "priceTexts":
            [
                {
                    "priceText": "This is the price",
                    "priceTextOffline": "Show this price text when offline!",
                    "language": "en"
                },
                {
                    "priceText": "Dit is de prijs",
                    "priceTextOffline": "Laat dit zien wanneer de charging station offline is!",
                    "language": "nl"
                },
                {
                    "priceText": "Dette er prisen",
                    "priceTextOffline": "Vis denne pristeksten når du er frakoblet",
                    "language": "nb_NO"
                }
            ]
        },
        "TimeOffset": "02:00",
        "NextTimeOffsetTransitionDateTime": "2024-01-01T00:00:00",
        "TimeOffsetNextTransition": "01:00",
        "CustomIdleFeeAfterStop": false,
        "SupportedLanguages": "en, nl, de, nb_NO",
        "CustomMultiLanguageMessages": true,
        "Language": "en",
        "WaitForSetUserPriceTimeout": 5000
    }
}

=== hyndex/DC-OCPP/configs/ocpp/v16/config.json
{
    "Internal": {
        "LogMessagesFormat": []
    },
    "Core": {
        "AuthorizationCacheEnabled": true,
        "AuthorizeRemoteTxRequests": false,
        "ClockAlignedDataInterval": 900,
        "ConnectionTimeOut": 10,
        "ConnectorPhaseRotation": "1.RST",
        "GetConfigurationMaxKeys": 100,
        "HeartbeatInterval": 86400,
        "LocalAuthorizeOffline": false,
        "LocalPreAuthorize": false,
        "MeterValuesAlignedData": "Energy.Active.Import.Register,Power.Active.Import,Voltage,Current.Import",
        "MeterValuesSampledData": "Energy.Active.Import.Register,Power.Active.Import,Voltage,Current.Import",
        "MeterValueSampleInterval": 0,
        "MinimumStatusDuration": 0,
        "NumberOfConnectors": 1,
        "ResetRetries": 1,
        "StopTransactionOnEVSideDisconnect": true,
        "StopTransactionOnInvalidId": true,
        "StopTxnAlignedData": "Energy.Active.Import.Register,Power.Active.Import,Voltage,Current.Import",
        "StopTxnSampledData": "Energy.Active.Import.Register,Power.Active.Import,Voltage,Current.Import",
        "SupportedFeatureProfiles": "Core,FirmwareManagement,RemoteTrigger,Reservation,LocalAuthListManagement,SmartCharging",
        "TransactionMessageAttempts": 1,
        "TransactionMessageRetryInterval": 10,
        "UnlockConnectorOnEVSideDisconnect": true
    },
    "FirmwareManagement": {
        "SupportedFileTransferProtocols": "FTP"
    },
    "LocalAuthListManagement": {
        "LocalAuthListEnabled": true,
        "LocalAuthListMaxLength": 42,
        "SendLocalListMaxLength": 42
    },
    "SmartCharging": {
        "ChargeProfileMaxStackLevel": 42,
        "ChargingScheduleAllowedChargingRateUnit": "Current",
        "ChargingScheduleMaxPeriods": 42,
        "MaxChargingProfilesInstalled": 42
    },
    "Security": {
        "SecurityProfile": 0
    },
    "PnC": {
        "ISO15118CertificateManagementEnabled": true,
        "ISO15118PnCEnabled": true,
        "ContractValidationOffline": true
    },
    "CostAndPrice": {
        "CustomDisplayCostAndPrice": false
    }
}

=== hyndex/DC-OCPP/configs/ocpp/v16/config-docker-tls.json
{
    "Internal": {
        "ChargePointId": "cp001",
        "CentralSystemURI": "127.0.0.1:8443/steve/websocket/CentralSystemService/",
        "ChargeBoxSerialNumber": "cp001",
        "ChargePointModel": "Yeti",
        "ChargePointVendor": "Pionix",
        "FirmwareVersion": "0.1"
    },
    "Core": {
        "AuthorizeRemoteTxRequests": false,
        "ClockAlignedDataInterval": 900,
        "ConnectionTimeOut": 10,
        "ConnectorPhaseRotation": "0.RST,1.RST",
        "GetConfigurationMaxKeys": 100,
        "HeartbeatInterval": 86400,
        "LocalAuthorizeOffline": false,
        "LocalPreAuthorize": false,
        "MeterValuesAlignedData": "Energy.Active.Import.Register",
        "MeterValuesSampledData": "Energy.Active.Import.Register",
        "MeterValueSampleInterval": 0,
        "NumberOfConnectors": 1,
        "ResetRetries": 1,
        "StopTransactionOnInvalidId": true,
        "StopTxnAlignedData": "Energy.Active.Import.Register",
        "StopTxnSampledData": "Energy.Active.Import.Register",
        "SupportedFeatureProfiles": "Core,FirmwareManagement,Reservation,RemoteTrigger,LocalAuthListManagement,SmartCharging",
        "TransactionMessageAttempts": 1,
        "TransactionMessageRetryInterval": 10,
        "UnlockConnectorOnEVSideDisconnect": true
    },
    "FirmwareManagement": {
        "SupportedFileTransferProtocols": "FTP,FTPS,HTTP,HTTPS"
    },
    "Security": {
        "AuthorizationKey": "AABBCCDDEEFFGGHH",
        "SecurityProfile": 2
    },
    "LocalAuthListManagement": {
        "LocalAuthListEnabled": true,
        "LocalAuthListMaxLength": 42,
        "SendLocalListMaxLength": 42
    },
    "SmartCharging": {
        "ChargeProfileMaxStackLevel": 42,
        "ChargingScheduleAllowedChargingRateUnit": "Current",
        "ChargingScheduleMaxPeriods": 42,
        "MaxChargingProfilesInstalled": 42
    },
    "Custom": {
        "ExampleConfigurationKey": "example"
    }
}

=== hyndex/DC-OCPP/configs/ocpp/v16/config-docker.json
{
    "Internal": {
        "ChargePointId": "cp001",
        "CentralSystemURI": "127.0.0.1:8180/steve/websocket/CentralSystemService/",
        "ChargeBoxSerialNumber": "cp001",
        "ChargePointModel": "Yeti",
        "ChargePointVendor": "Pionix",
        "FirmwareVersion": "0.1",
        "AllowChargingProfileWithoutStartSchedule": true,
        "UseTPM" : false,
        "LogMessagesFormat": ["html","security"]
    },
    "Core": {
        "AuthorizeRemoteTxRequests": false,
        "ClockAlignedDataInterval": 900,
        "ConnectionTimeOut": 30,
        "ConnectorPhaseRotation": "0.RST,1.RST",
        "GetConfigurationMaxKeys": 100,
        "HeartbeatInterval": 86400,
        "LocalAuthorizeOffline": false,
        "LocalPreAuthorize": false,
        "MeterValuesAlignedData": "Energy.Active.Import.Register",
        "MeterValuesSampledData": "Energy.Active.Import.Register,SoC",
        "MeterValueSampleInterval": 60,
        "NumberOfConnectors": 1,
        "ResetRetries": 1,
        "StopTransactionOnInvalidId": true,
        "StopTxnAlignedData": "Energy.Active.Import.Register",
        "StopTxnSampledData": "Energy.Active.Import.Register",
        "SupportedFeatureProfiles": "Core,FirmwareManagement,RemoteTrigger,Reservation,LocalAuthListManagement,SmartCharging",
        "TransactionMessageAttempts": 1,
        "TransactionMessageRetryInterval": 10,
        "UnlockConnectorOnEVSideDisconnect": true,
        "WebSocketPingInterval": 10
    },
    "FirmwareManagement": {
        "SupportedFileTransferProtocols": "FTP,FTPS,HTTP,HTTPS"
    },
    "Security": {
        "CpoName": "Pionix",
        "AuthorizationKey": "AABBCCDDEEFFGGHH",
        "SecurityProfile": 1
    },
    "LocalAuthListManagement": {
        "LocalAuthListEnabled": true,
        "LocalAuthListMaxLength": 42,
        "SendLocalListMaxLength": 42
    },
    "SmartCharging": {
        "ChargeProfileMaxStackLevel": 42,
        "ChargingScheduleAllowedChargingRateUnit": "Current,Power",
        "ChargingScheduleMaxPeriods": 42,
        "MaxChargingProfilesInstalled": 42
    },
    "CostAndPrice": {
        "CustomDisplayCostAndPrice": false
    },
    "Custom": {
        "ExampleConfigurationKey": "example"
    }
}
